spring.application.name=BackEnd

#Database Settings
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/netflix?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = Ijse@1234
spring.datasource.hikari.maximum-pool-size = 10

#JPA Settings
spring.jpa.generate-ddl = true
spring.jpa.show-sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto = update

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=netfliix577@gmail.com
spring.mail.password=dprs jfln mmni tjlz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#clerk
clerk.backend.api=https://api.clerk.com
clerk.secretKey=sk_test_kNxOIjc11DlUrJqto0B2SkVowYTWZDRhUIXkOpxloj
clerk.pem.public.key=pk_test_YXNzdXJlZC1tYXlmbHktOTMuY2xlcmsuYWNjb3VudHMuZGV2JA
